# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(860, 646)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget *widget= new QWidget(this);\n"
"QPushButton *btn1 = new QPushButton();\n"
"QPushButton *btn2 = new QPushButton();\n"
"QPushButton *btn3 = new QPushButton();\n"
"QHBoxLayout *horizontal_bottom = new QHBoxLayout();\n"
"\n"
"  horizontal_bottom->setSpacing(0);\n"
"  horizontal_bottom->addWidget(btn1 );\n"
"  horizontal_bottom->addWidget(btn2);\n"
"  horizontal_bottom->addWidget(btn3);\n"
"  horizontal_bottom->setContentsMargins(0,0,0,0);\n"
"  widget->setLayout(horizontal_bottom);")
        self.centralwidget.setObjectName("centralwidget")
        self.pages_stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages_stack.setGeometry(QtCore.QRect(0, -10, 851, 651))
        self.pages_stack.setStyleSheet("QWidget *widget= new QWidget(this);\n"
"QPushButton *btn1 = new QPushButton();\n"
"QPushButton *btn2 = new QPushButton();\n"
"QPushButton *btn3 = new QPushButton();\n"
"QHBoxLayout *horizontal_bottom = new QHBoxLayout();\n"
"\n"
"  horizontal_bottom->setSpacing(0);\n"
"  horizontal_bottom->addWidget(btn1 );\n"
"  horizontal_bottom->addWidget(btn2);\n"
"  horizontal_bottom->addWidget(btn3);\n"
"  horizontal_bottom->setContentsMargins(0,0,0,0);\n"
"  widget->setLayout(horizontal_bottom);")
        self.pages_stack.setObjectName("pages_stack")
        self.singin_page = QtWidgets.QWidget()
        self.singin_page.setBaseSize(QtCore.QSize(0, 0))
        self.singin_page.setObjectName("singin_page")
        self.widget_9 = QtWidgets.QWidget(self.singin_page)
        self.widget_9.setGeometry(QtCore.QRect(0, -10, 854, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.username_textinput = QtWidgets.QLineEdit(self.widget_9)
        self.username_textinput.setGeometry(QtCore.QRect(260, 290, 321, 41))
        self.username_textinput.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.username_textinput.setText("")
        self.username_textinput.setObjectName("username_textinput")
        self.signup_button = QtWidgets.QPushButton(self.widget_9)
        self.signup_button.setGeometry(QtCore.QRect(460, 580, 75, 23))
        self.signup_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #f0f0f0;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: ;\n"
"}")
        self.signup_button.setObjectName("signup_button")
        self.login_button = QtWidgets.QPushButton(self.widget_9)
        self.login_button.setGeometry(QtCore.QRect(350, 500, 141, 51))
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setAutoFillBackground(False)
        self.login_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #121212  ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:   ;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.label_33 = QtWidgets.QLabel(self.widget_9)
        self.label_33.setGeometry(QtCore.QRect(340, 30, 181, 181))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.widget_9)
        self.label_34.setGeometry(QtCore.QRect(260, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setObjectName("label_34")
        self.password_textinput = QtWidgets.QLineEdit(self.widget_9)
        self.password_textinput.setGeometry(QtCore.QRect(260, 410, 321, 41))
        self.password_textinput.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.password_textinput.setText("")
        self.password_textinput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_textinput.setObjectName("password_textinput")
        self.label_35 = QtWidgets.QLabel(self.widget_9)
        self.label_35.setGeometry(QtCore.QRect(270, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.widget_9)
        self.label_36.setGeometry(QtCore.QRect(320, 580, 121, 21))
        self.label_36.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"color: rgb(255, 53, 97);")
        self.label_36.setObjectName("label_36")
        self.invalid_signin_label = QtWidgets.QLabel(self.widget_9)
        self.invalid_signin_label.setGeometry(QtCore.QRect(270, 460, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.invalid_signin_label.setFont(font)
        self.invalid_signin_label.setStyleSheet("color: red;")
        self.invalid_signin_label.setObjectName("invalid_signin_label")
        self.pages_stack.addWidget(self.singin_page)
        self.registration_page = QtWidgets.QWidget()
        self.registration_page.setObjectName("registration_page")
        self.widget_10 = QtWidgets.QWidget(self.registration_page)
        self.widget_10.setGeometry(QtCore.QRect(0, -10, 854, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_19.setGeometry(QtCore.QRect(150, 290, 321, 41))
        self.lineEdit_19.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_21.setGeometry(QtCore.QRect(460, 580, 75, 23))
        self.pushButton_21.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(18, 18, 18);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_22.setGeometry(QtCore.QRect(400, 490, 141, 51))
        self.pushButton_22.setAutoFillBackground(False)
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #121212  ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:   ;\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_37 = QtWidgets.QLabel(self.widget_10)
        self.label_37.setGeometry(QtCore.QRect(340, 30, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.widget_10)
        self.label_38.setGeometry(QtCore.QRect(150, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_38.setObjectName("label_38")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_20.setGeometry(QtCore.QRect(150, 410, 321, 41))
        self.lineEdit_20.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.lineEdit_20.setText("")
        self.lineEdit_20.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_39 = QtWidgets.QLabel(self.widget_10)
        self.label_39.setGeometry(QtCore.QRect(150, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.widget_10)
        self.label_40.setGeometry(QtCore.QRect(320, 580, 121, 21))
        self.label_40.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"color: rgb(255, 53, 97);")
        self.label_40.setObjectName("label_40")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        self.widget_11.setGeometry(QtCore.QRect(0, 0, 901, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.username_textinput_2 = QtWidgets.QLineEdit(self.widget_11)
        self.username_textinput_2.setGeometry(QtCore.QRect(170, 380, 501, 41))
        self.username_textinput_2.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.username_textinput_2.setText("")
        self.username_textinput_2.setObjectName("username_textinput_2")
        self.label_41 = QtWidgets.QLabel(self.widget_11)
        self.label_41.setGeometry(QtCore.QRect(340, 30, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.widget_11)
        self.label_42.setGeometry(QtCore.QRect(180, 330, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_42.setObjectName("label_42")
        self.password_textinput_2 = QtWidgets.QLineEdit(self.widget_11)
        self.password_textinput_2.setGeometry(QtCore.QRect(170, 500, 501, 41))
        self.password_textinput_2.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.password_textinput_2.setText("")
        self.password_textinput_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_textinput_2.setObjectName("password_textinput_2")
        self.label_43 = QtWidgets.QLabel(self.widget_11)
        self.label_43.setGeometry(QtCore.QRect(180, 450, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_43.setObjectName("label_43")
        self.name_textinput = QtWidgets.QLineEdit(self.widget_11)
        self.name_textinput.setGeometry(QtCore.QRect(170, 260, 501, 41))
        self.name_textinput.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.name_textinput.setText("")
        self.name_textinput.setObjectName("name_textinput")
        self.label_44 = QtWidgets.QLabel(self.widget_11)
        self.label_44.setGeometry(QtCore.QRect(180, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_44.setObjectName("label_44")
        self.registration_button = QtWidgets.QPushButton(self.widget_11)
        self.registration_button.setGeometry(QtCore.QRect(350, 570, 141, 51))
        self.registration_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registration_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #121212  ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:   ;\n"
"}")
        self.registration_button.setObjectName("registration_button")
        self.invalid_username_label = QtWidgets.QLabel(self.widget_11)
        self.invalid_username_label.setGeometry(QtCore.QRect(500, 330, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.invalid_username_label.setFont(font)
        self.invalid_username_label.setStyleSheet("color: red;")
        self.invalid_username_label.setObjectName("invalid_username_label")
        self.pages_stack.addWidget(self.registration_page)
        self.chatting_page = QtWidgets.QWidget()
        self.chatting_page.setObjectName("chatting_page")
        self.buttons_3 = QtWidgets.QWidget(self.chatting_page)
        self.buttons_3.setGeometry(QtCore.QRect(0, -10, 91, 691))
        self.buttons_3.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.buttons_3.setObjectName("buttons_3")
        self.chatting_chatting_button = QtWidgets.QPushButton(self.buttons_3)
        self.chatting_chatting_button.setGeometry(QtCore.QRect(0, 30, 91, 61))
        self.chatting_chatting_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chatting_chatting_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Vector.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"color: transparent\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../GUI desgin/GUI desgin/setting/icons/Vector.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatting_chatting_button.setIcon(icon)
        self.chatting_chatting_button.setIconSize(QtCore.QSize(50, 50))
        self.chatting_chatting_button.setObjectName("chatting_chatting_button")
        self.chatting_requests_button = QtWidgets.QPushButton(self.buttons_3)
        self.chatting_requests_button.setGeometry(QtCore.QRect(0, 100, 91, 61))
        self.chatting_requests_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chatting_requests_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Group 1.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"color: transparent\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../GUI desgin/GUI desgin/setting/icons/Group 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatting_requests_button.setIcon(icon1)
        self.chatting_requests_button.setIconSize(QtCore.QSize(50, 50))
        self.chatting_requests_button.setObjectName("chatting_requests_button")
        self.chatting_exit_button = QtWidgets.QPushButton(self.buttons_3)
        self.chatting_exit_button.setGeometry(QtCore.QRect(0, 590, 81, 61))
        self.chatting_exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chatting_exit_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Sign-out.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"color: transparent\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../GUI desgin/GUI desgin/setting/icons/Sign-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatting_exit_button.setIcon(icon2)
        self.chatting_exit_button.setIconSize(QtCore.QSize(50, 50))
        self.chatting_exit_button.setObjectName("chatting_exit_button")
        self.line = QtWidgets.QFrame(self.buttons_3)
        self.line.setGeometry(QtCore.QRect(80, 20, 20, 641))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.chatting_settings_button = QtWidgets.QPushButton(self.buttons_3)
        self.chatting_settings_button.setGeometry(QtCore.QRect(0, 170, 91, 61))
        self.chatting_settings_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chatting_settings_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/icons/icons/settings.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"color: transparent\n"
"}")
        self.chatting_settings_button.setIcon(icon1)
        self.chatting_settings_button.setIconSize(QtCore.QSize(50, 50))
        self.chatting_settings_button.setObjectName("chatting_settings_button")
        self.chatting_settings_button.raise_()
        self.chatting_chatting_button.raise_()
        self.chatting_requests_button.raise_()
        self.chatting_exit_button.raise_()
        self.line.raise_()
        self.persons_3 = QtWidgets.QWidget(self.chatting_page)
        self.persons_3.setGeometry(QtCore.QRect(90, 0, 251, 651))
        self.persons_3.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.persons_3.setObjectName("persons_3")
        self.label_45 = QtWidgets.QLabel(self.persons_3)
        self.label_45.setGeometry(QtCore.QRect(30, 20, 161, 41))
        self.label_45.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 28pt \"MS Shell Dlg 2\";")
        self.label_45.setObjectName("label_45")
        self.rooms_scrollArea = QtWidgets.QScrollArea(self.persons_3)
        self.rooms_scrollArea.setGeometry(QtCore.QRect(0, 80, 241, 571))
        self.rooms_scrollArea.setStyleSheet("QScrollArea{\n"
"    border: none;\n"
"}")
        self.rooms_scrollArea.setWidgetResizable(True)
        self.rooms_scrollArea.setObjectName("rooms_scrollArea")
        self.rooms_scrollArea_contents = QtWidgets.QWidget()
        self.rooms_scrollArea_contents.setGeometry(QtCore.QRect(0, 0, 241, 571))
        self.rooms_scrollArea_contents.setObjectName("rooms_scrollArea_contents")
        self.room = QtWidgets.QWidget(self.rooms_scrollArea_contents)
        self.room.setGeometry(QtCore.QRect(0, 0, 251, 71))
        self.room.setObjectName("room")
        self.avatar = QtWidgets.QWidget(self.room)
        self.avatar.setGeometry(QtCore.QRect(0, 0, 81, 61))
        self.avatar.setStyleSheet("QWidget{\n"
"background-image:url(:/images/images/User_cicrle_duotone 72x72.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.avatar.setObjectName("avatar")
        self.room_name_label = QtWidgets.QLabel(self.room)
        self.room_name_label.setGeometry(QtCore.QRect(90, 10, 47, 13))
        self.room_name_label.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-weight: 500\n"
"}")
        self.room_name_label.setObjectName("room_name_label")
        self.room_username_label = QtWidgets.QLabel(self.room)
        self.room_username_label.setGeometry(QtCore.QRect(90, 40, 47, 13))
        self.room_username_label.setStyleSheet("QLabel{\n"
"color: #A0A0A0;\n"
"}")
        self.room_username_label.setObjectName("room_username_label")
        self.room_clickable_button = QtWidgets.QPushButton(self.room)
        self.room_clickable_button.setGeometry(QtCore.QRect(0, -10, 251, 81))
        self.room_clickable_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.room_clickable_button.setText("")
        self.room_clickable_button.setObjectName("room_clickable_button")
        self.room_clickable_button.raise_()
        self.avatar.raise_()
        self.room_name_label.raise_()
        self.room_username_label.raise_()
        self.rooms_scrollArea.setWidget(self.rooms_scrollArea_contents)
        self.line_2 = QtWidgets.QFrame(self.persons_3)
        self.line_2.setGeometry(QtCore.QRect(0, 60, 251, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.persons_3)
        self.line_3.setGeometry(QtCore.QRect(240, 20, 20, 641))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2.raise_()
        self.label_45.raise_()
        self.rooms_scrollArea.raise_()
        self.line_3.raise_()
        self.widget_12 = QtWidgets.QWidget(self.chatting_page)
        self.widget_12.setGeometry(QtCore.QRect(340, -10, 521, 651))
        self.widget_12.setObjectName("widget_12")
        self.no_rooms_label = QtWidgets.QLabel(self.widget_12)
        self.no_rooms_label.setGeometry(QtCore.QRect(30, 300, 461, 41))
        self.no_rooms_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.no_rooms_label.setObjectName("no_rooms_label")
        self.messages_scrollarea = QtWidgets.QScrollArea(self.widget_12)
        self.messages_scrollarea.setGeometry(QtCore.QRect(9, 80, 501, 521))
        self.messages_scrollarea.setWidgetResizable(True)
        self.messages_scrollarea.setObjectName("messages_scrollarea")
        self.messages_scrollarea_contents = QtWidgets.QWidget()
        self.messages_scrollarea_contents.setGeometry(QtCore.QRect(0, 0, 499, 519))
        self.messages_scrollarea_contents.setObjectName("messages_scrollarea_contents")
        self.receiver_message = QtWidgets.QWidget(self.messages_scrollarea_contents)
        self.receiver_message.setGeometry(QtCore.QRect(320, 50, 171, 41))
        self.receiver_message.setStyleSheet("QWidget{\n"
"background-color: #BB86FC;\n"
"border-radius: 8px\n"
"}")
        self.receiver_message.setObjectName("receiver_message")
        self.receiver_message_content = QtWidgets.QLabel(self.receiver_message)
        self.receiver_message_content.setGeometry(QtCore.QRect(-10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.receiver_message_content.setFont(font)
        self.receiver_message_content.setStyleSheet("QLabel{\n"
"color: #E0E0E0;\n"
"font-weight: 500;\n"
"}")
        self.receiver_message_content.setObjectName("receiver_message_content")
        self.receiver_message_date = QtWidgets.QLabel(self.receiver_message)
        self.receiver_message_date.setGeometry(QtCore.QRect(140, 30, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.receiver_message_date.setFont(font)
        self.receiver_message_date.setStyleSheet("color: white")
        self.receiver_message_date.setObjectName("receiver_message_date")
        self.sender_message = QtWidgets.QWidget(self.messages_scrollarea_contents)
        self.sender_message.setGeometry(QtCore.QRect(10, 110, 91, 41))
        self.sender_message.setStyleSheet("QWidget{\n"
"background-color: rgb(30, 30, 30);\n"
"border-radius: 8px\n"
"}")
        self.sender_message.setObjectName("sender_message")
        self.sender_message_content = QtWidgets.QLabel(self.sender_message)
        self.sender_message_content.setGeometry(QtCore.QRect(0, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.sender_message_content.setFont(font)
        self.sender_message_content.setStyleSheet("QLabel{\n"
"color: #E0E0E0;\n"
"font-weight: 500;\n"
"}")
        self.sender_message_content.setObjectName("sender_message_content")
        self.sender_message_date = QtWidgets.QLabel(self.sender_message)
        self.sender_message_date.setGeometry(QtCore.QRect(40, 30, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.sender_message_date.setFont(font)
        self.sender_message_date.setStyleSheet("color: white")
        self.sender_message_date.setObjectName("sender_message_date")
        self.messages_scrollarea.setWidget(self.messages_scrollarea_contents)
        self.widget = QtWidgets.QWidget(self.widget_12)
        self.widget.setGeometry(QtCore.QRect(-1, 20, 531, 641))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-1, 0, 541, 61))
        self.widget_2.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.widget_2.setObjectName("widget_2")
        self.message_box = QtWidgets.QWidget(self.widget_2)
        self.message_box.setGeometry(QtCore.QRect(-1, 10, 261, 51))
        self.message_box.setObjectName("message_box")
        self.message_box_avatar = QtWidgets.QWidget(self.message_box)
        self.message_box_avatar.setGeometry(QtCore.QRect(10, 0, 71, 41))
        self.message_box_avatar.setStyleSheet("QWidget{\n"
"background-image:url(:/images/images/User_cicrle_duotone 48x48.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.message_box_avatar.setObjectName("message_box_avatar")
        self.message_box_name_label = QtWidgets.QLabel(self.message_box)
        self.message_box_name_label.setGeometry(QtCore.QRect(80, 0, 121, 16))
        self.message_box_name_label.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-weight: 500\n"
"}")
        self.message_box_name_label.setObjectName("message_box_name_label")
        self.message_box_status = QtWidgets.QLabel(self.message_box)
        self.message_box_status.setGeometry(QtCore.QRect(80, 20, 47, 13))
        self.message_box_status.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.message_box_status.setObjectName("message_box_status")
        self.widget.raise_()
        self.no_rooms_label.raise_()
        self.messages_scrollarea.raise_()
        self.widget_3 = QtWidgets.QWidget(self.chatting_page)
        self.widget_3.setGeometry(QtCore.QRect(340, 600, 521, 51))
        self.widget_3.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.widget_3.setObjectName("widget_3")
        self.sned_textinput = QtWidgets.QLineEdit(self.widget_3)
        self.sned_textinput.setGeometry(QtCore.QRect(10, 0, 431, 51))
        self.sned_textinput.setObjectName("sned_textinput")
        self.send_message_button = QtWidgets.QPushButton(self.widget_3)
        self.send_message_button.setGeometry(QtCore.QRect(440, 0, 61, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_message_button.sizePolicy().hasHeightForWidth())
        self.send_message_button.setSizePolicy(sizePolicy)
        self.send_message_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_message_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Send_hor 48x48.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"border: none;\n"
"}")
        self.send_message_button.setText("")
        self.send_message_button.setObjectName("send_message_button")
        self.pages_stack.addWidget(self.chatting_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.widget_4 = QtWidgets.QWidget(self.settings_page)
        self.widget_4.setGeometry(QtCore.QRect(0, 10, 81, 651))
        self.widget_4.setObjectName("widget_4")
        self.buttons_5 = QtWidgets.QWidget(self.widget_4)
        self.buttons_5.setGeometry(QtCore.QRect(-10, -10, 91, 691))
        self.buttons_5.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.buttons_5.setObjectName("buttons_5")
        self.settings_chatting_button = QtWidgets.QPushButton(self.buttons_5)
        self.settings_chatting_button.setGeometry(QtCore.QRect(0, 30, 91, 61))
        self.settings_chatting_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_chatting_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Vector.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.settings_chatting_button.setText("")
        self.settings_chatting_button.setIcon(icon)
        self.settings_chatting_button.setIconSize(QtCore.QSize(50, 50))
        self.settings_chatting_button.setObjectName("settings_chatting_button")
        self.settings_requests_button = QtWidgets.QPushButton(self.buttons_5)
        self.settings_requests_button.setGeometry(QtCore.QRect(0, 100, 91, 61))
        self.settings_requests_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_requests_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Group 1.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.settings_requests_button.setText("")
        self.settings_requests_button.setIcon(icon1)
        self.settings_requests_button.setIconSize(QtCore.QSize(50, 50))
        self.settings_requests_button.setObjectName("settings_requests_button")
        self.settings_exit_button = QtWidgets.QPushButton(self.buttons_5)
        self.settings_exit_button.setGeometry(QtCore.QRect(0, 590, 81, 61))
        self.settings_exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_exit_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Sign-out.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.settings_exit_button.setText("")
        self.settings_exit_button.setIcon(icon2)
        self.settings_exit_button.setIconSize(QtCore.QSize(50, 50))
        self.settings_exit_button.setObjectName("settings_exit_button")
        self.line_6 = QtWidgets.QFrame(self.buttons_5)
        self.line_6.setGeometry(QtCore.QRect(80, 20, 20, 641))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.settings_settings_button = QtWidgets.QPushButton(self.buttons_5)
        self.settings_settings_button.setGeometry(QtCore.QRect(0, 170, 91, 61))
        self.settings_settings_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_settings_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/icons/icons/settings.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.settings_settings_button.setText("")
        self.settings_settings_button.setIcon(icon1)
        self.settings_settings_button.setIconSize(QtCore.QSize(50, 50))
        self.settings_settings_button.setObjectName("settings_settings_button")
        self.label = QtWidgets.QLabel(self.settings_page)
        self.label.setGeometry(QtCore.QRect(280, 260, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.pages_stack.addWidget(self.settings_page)
        self.requests_page = QtWidgets.QWidget()
        self.requests_page.setObjectName("requests_page")
        self.widget_16 = QtWidgets.QWidget(self.requests_page)
        self.widget_16.setGeometry(QtCore.QRect(340, 20, 521, 651))
        self.widget_16.setObjectName("widget_16")
        self.label_60 = QtWidgets.QLabel(self.widget_16)
        self.label_60.setGeometry(QtCore.QRect(120, 70, 251, 41))
        self.label_60.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.label_60.setObjectName("label_60")
        self.send_button_2 = QtWidgets.QLineEdit(self.widget_16)
        self.send_button_2.setGeometry(QtCore.QRect(20, 200, 321, 41))
        self.send_button_2.setStatusTip("")
        self.send_button_2.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid #cccccc; \n"
"    border-radius: 10px;       \n"
"    padding: 5px;            \n"
"    background-color: #121212;  \n"
"\n"
"}\n"
"")
        self.send_button_2.setText("")
        self.send_button_2.setObjectName("send_button_2")
        self.send_button = QtWidgets.QPushButton(self.widget_16)
        self.send_button.setGeometry(QtCore.QRect(360, 200, 121, 41))
        self.send_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_button.setAutoFillBackground(False)
        self.send_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #121212  ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:   ;\n"
"}")
        self.send_button.setObjectName("send_button")
        self.friend_request_label = QtWidgets.QLabel(self.widget_16)
        self.friend_request_label.setGeometry(QtCore.QRect(30, 260, 191, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.friend_request_label.setFont(font)
        self.friend_request_label.setStyleSheet("color: white;\n"
"background: transparent")
        self.friend_request_label.setObjectName("friend_request_label")
        self.widget_6 = QtWidgets.QWidget(self.widget_16)
        self.widget_6.setGeometry(QtCore.QRect(120, 330, 211, 201))
        self.widget_6.setStyleSheet("QWidget{\n"
"background-image: url(:/images/images/Untitled design 250x250.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.persons_4 = QtWidgets.QWidget(self.requests_page)
        self.persons_4.setGeometry(QtCore.QRect(90, 10, 251, 651))
        self.persons_4.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.persons_4.setObjectName("persons_4")
        self.label_59 = QtWidgets.QLabel(self.persons_4)
        self.label_59.setGeometry(QtCore.QRect(20, 10, 241, 41))
        self.label_59.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.label_59.setObjectName("label_59")
        self.request_scrollArea = QtWidgets.QScrollArea(self.persons_4)
        self.request_scrollArea.setGeometry(QtCore.QRect(10, 60, 231, 581))
        self.request_scrollArea.setWidgetResizable(True)
        self.request_scrollArea.setObjectName("request_scrollArea")
        self.request_scrollArea_contents = QtWidgets.QWidget()
        self.request_scrollArea_contents.setGeometry(QtCore.QRect(0, 0, 229, 579))
        self.request_scrollArea_contents.setObjectName("request_scrollArea_contents")
        self.request_box = QtWidgets.QWidget(self.request_scrollArea_contents)
        self.request_box.setGeometry(QtCore.QRect(0, 0, 231, 161))
        self.request_box.setObjectName("request_box")
        self.label_2 = QtWidgets.QLabel(self.request_box)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.requester_name = QtWidgets.QLabel(self.request_box)
        self.requester_name.setGeometry(QtCore.QRect(10, 30, 211, 16))
        self.requester_name.setStyleSheet("color: white")
        self.requester_name.setObjectName("requester_name")
        self.requester_date = QtWidgets.QLabel(self.request_box)
        self.requester_date.setGeometry(QtCore.QRect(10, 70, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.requester_date.setFont(font)
        self.requester_date.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.requester_date.setWordWrap(True)
        self.requester_date.setObjectName("requester_date")
        self.requests_buttons = QtWidgets.QWidget(self.request_box)
        self.requests_buttons.setGeometry(QtCore.QRect(20, 110, 181, 41))
        self.requests_buttons.setObjectName("requests_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.requests_buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.request_accept_button = QtWidgets.QPushButton(self.requests_buttons)
        self.request_accept_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.request_accept_button.setStyleSheet("background-color: #444444;\n"
"color: #E0E0E0;\n"
"border-radius: 5px;\n"
"width: 70px;\n"
"height: 35px;")
        self.request_accept_button.setObjectName("request_accept_button")
        self.horizontalLayout.addWidget(self.request_accept_button)
        spacerItem = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.request_decline_button = QtWidgets.QPushButton(self.requests_buttons)
        self.request_decline_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.request_decline_button.setStyleSheet("QPushButton{\n"
"background-color: #CF6679;\n"
"color: #E0E0E0;\n"
"border-radius: 5px;\n"
"width: 70px;\n"
"height: 35px;\n"
"}")
        self.request_decline_button.setObjectName("request_decline_button")
        self.horizontalLayout.addWidget(self.request_decline_button)
        self.requester_username = QtWidgets.QLabel(self.request_box)
        self.requester_username.setGeometry(QtCore.QRect(10, 50, 211, 16))
        self.requester_username.setStyleSheet("color: #A0A0A0")
        self.requester_username.setObjectName("requester_username")
        self.line_4 = QtWidgets.QFrame(self.request_box)
        self.line_4.setGeometry(QtCore.QRect(0, 150, 231, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.no_requests_label = QtWidgets.QLabel(self.request_scrollArea_contents)
        self.no_requests_label.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.no_requests_label.setFont(font)
        self.no_requests_label.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.no_requests_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_requests_label.setObjectName("no_requests_label")
        self.no_requests_label.raise_()
        self.request_box.raise_()
        self.request_scrollArea.setWidget(self.request_scrollArea_contents)
        self.widget_5 = QtWidgets.QWidget(self.requests_page)
        self.widget_5.setGeometry(QtCore.QRect(0, 10, 91, 651))
        self.widget_5.setObjectName("widget_5")
        self.buttons_4 = QtWidgets.QWidget(self.widget_5)
        self.buttons_4.setGeometry(QtCore.QRect(-10, 0, 91, 691))
        self.buttons_4.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.buttons_4.setObjectName("buttons_4")
        self.requests_chatting_button = QtWidgets.QPushButton(self.buttons_4)
        self.requests_chatting_button.setGeometry(QtCore.QRect(0, 30, 91, 61))
        self.requests_chatting_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.requests_chatting_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Vector.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.requests_chatting_button.setText("")
        self.requests_chatting_button.setIcon(icon)
        self.requests_chatting_button.setIconSize(QtCore.QSize(50, 50))
        self.requests_chatting_button.setObjectName("requests_chatting_button")
        self.requests_requests_button = QtWidgets.QPushButton(self.buttons_4)
        self.requests_requests_button.setGeometry(QtCore.QRect(0, 100, 91, 61))
        self.requests_requests_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.requests_requests_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Group 1.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.requests_requests_button.setText("")
        self.requests_requests_button.setIcon(icon1)
        self.requests_requests_button.setIconSize(QtCore.QSize(50, 50))
        self.requests_requests_button.setObjectName("requests_requests_button")
        self.requests_exit_button = QtWidgets.QPushButton(self.buttons_4)
        self.requests_exit_button.setGeometry(QtCore.QRect(0, 590, 81, 61))
        self.requests_exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.requests_exit_button.setStyleSheet("QPushButton{\n"
"background-image:url(:/icons/icons/Sign-out.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.requests_exit_button.setText("")
        self.requests_exit_button.setIcon(icon2)
        self.requests_exit_button.setIconSize(QtCore.QSize(50, 50))
        self.requests_exit_button.setObjectName("requests_exit_button")
        self.line_7 = QtWidgets.QFrame(self.buttons_4)
        self.line_7.setGeometry(QtCore.QRect(76, 20, 16, 641))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.requests_settings_button = QtWidgets.QPushButton(self.buttons_4)
        self.requests_settings_button.setGeometry(QtCore.QRect(0, 170, 91, 61))
        self.requests_settings_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.requests_settings_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/icons/icons/settings.png);\n"
" background-position: center;\n"
"background-size: 50px;\n"
" background-repeat: no-repeat;\n"
"}")
        self.requests_settings_button.setText("")
        self.requests_settings_button.setIcon(icon1)
        self.requests_settings_button.setIconSize(QtCore.QSize(50, 50))
        self.requests_settings_button.setObjectName("requests_settings_button")
        self.pages_stack.addWidget(self.requests_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages_stack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signup_button.setText(_translate("MainWindow", "Sign Up"))
        self.login_button.setText(_translate("MainWindow", "Sign In"))
        self.label_33.setText(_translate("MainWindow", "Sign In"))
        self.label_34.setText(_translate("MainWindow", "User Name"))
        self.label_35.setText(_translate("MainWindow", "Password"))
        self.label_36.setText(_translate("MainWindow", "Don\'t have an account"))
        self.invalid_signin_label.setText(_translate("MainWindow", "username or password is incorrect"))
        self.pushButton_21.setText(_translate("MainWindow", "Sign Up"))
        self.pushButton_22.setText(_translate("MainWindow", "Log In"))
        self.label_37.setText(_translate("MainWindow", "Sign Up"))
        self.label_38.setText(_translate("MainWindow", "User Name"))
        self.label_39.setText(_translate("MainWindow", "Password"))
        self.label_40.setText(_translate("MainWindow", "Don\'t have an account"))
        self.label_41.setText(_translate("MainWindow", "Sign Up"))
        self.label_42.setText(_translate("MainWindow", "User Name"))
        self.label_43.setText(_translate("MainWindow", "Password"))
        self.label_44.setText(_translate("MainWindow", " Name"))
        self.registration_button.setText(_translate("MainWindow", "Sign Up"))
        self.invalid_username_label.setText(_translate("MainWindow", " Username Already Taken"))
        self.chatting_chatting_button.setText(_translate("MainWindow", "Chatting"))
        self.chatting_requests_button.setText(_translate("MainWindow", "Requests"))
        self.chatting_exit_button.setText(_translate("MainWindow", "Exit"))
        self.chatting_settings_button.setText(_translate("MainWindow", "Settings"))
        self.label_45.setText(_translate("MainWindow", "Messages"))
        self.room_name_label.setText(_translate("MainWindow", "Name"))
        self.room_username_label.setText(_translate("MainWindow", "username"))
        self.no_rooms_label.setText(_translate("MainWindow", "Select a chat to start Messaging"))
        self.receiver_message_content.setText(_translate("MainWindow", "هنكمل شغل واله ايه"))
        self.receiver_message_date.setText(_translate("MainWindow", "9:28 AM"))
        self.sender_message_content.setText(_translate("MainWindow", "ماشي"))
        self.sender_message_date.setText(_translate("MainWindow", "9:28 AM"))
        self.message_box_name_label.setText(_translate("MainWindow", "Name"))
        self.message_box_status.setText(_translate("MainWindow", "status"))
        self.label.setText(_translate("MainWindow", "Coming Soon"))
        self.label_60.setText(_translate("MainWindow", "Find your friends"))
        self.send_button_2.setPlaceholderText(_translate("MainWindow", "Enter user name"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.friend_request_label.setText(_translate("MainWindow", "friend request status"))
        self.label_59.setText(_translate("MainWindow", "Friend requests"))
        self.label_2.setText(_translate("MainWindow", "Request:"))
        self.requester_name.setText(_translate("MainWindow", "Full Name"))
        self.requester_date.setText(_translate("MainWindow", "<html><head/><body><p>Send a request to chat with you <br/>at: date</p></body></html>"))
        self.request_accept_button.setText(_translate("MainWindow", "Accept"))
        self.request_decline_button.setText(_translate("MainWindow", "Decline"))
        self.requester_username.setText(_translate("MainWindow", "Username"))
        self.no_requests_label.setText(_translate("MainWindow", "No Requests"))
import assets.assets
